#!/usr/bin/env python3
"""Inline the Font Awesome icons used by the site as an SVG sprite.

The site used to load `assets/fontawesome/js/all.min.js` (1.73 MB) on every
page just to swap a handful of `<i class="fa-...">` placeholders for `<svg>`.
This script replaces that dependency at build-authoring time:

  * every `<i class="fa-solid fa-x"></i>` / `<i class="fa-brands fa-x"></i>`
    becomes `<svg class="svg-inline--fa"><use href="#fa-x"/></svg>`
  * a hidden `<svg>` sprite with the `<symbol>` definitions is inserted once per
    page, right after `<body>`

Icon geometry comes from the vendored Font Awesome metadata
(`assets/fontawesome/metadata/icons.json`), so the shapes stay identical.

Idempotent: running it again rewrites the sprite in place and leaves the
already-converted `<svg>` markup alone.

Usage: python3 scripts/build_icons.py [page.html ...]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
METADATA = REPO / "assets" / "fontawesome" / "metadata" / "icons.json"
DEFAULT_PAGES = [
    "index.html",
    "index-en.html",
    "impressum-datenschutz.html",
    "imprint-privacy.html",
]

# style -> Font Awesome prefix, used for the data-prefix attribute
PREFIX = {"solid": "fas", "regular": "far", "brands": "fab"}

ICON_RE = re.compile(r'<i class="(fa-(?:solid|brands|regular))\s+fa-([a-z0-9-]+)"\s*></i>')

# Icons that only appear in JavaScript (site-motion.js draws the back-to-top
# button) still need a symbol in every page's sprite.
ALWAYS = [("fa-solid", "arrow-up")]
SPRITE_RE = re.compile(
    r"\n?[ \t]*<!--\s*fa-sprite:start.*?<!--\s*fa-sprite:end\s*-->[ \t]*\n?", re.DOTALL
)
SPRITE_ANCHOR = "<body>\n"


def load_icons() -> dict:
    return json.loads(METADATA.read_text(encoding="utf-8"))


def icon_path(icons: dict, name: str, style: str) -> tuple[str, tuple[int, int, int, int]]:
    """Return (path-data, viewBox) for one icon in the given style."""
    entry = icons.get(name)
    if entry is None:
        raise SystemExit(f"unknown Font Awesome icon: {name}")
    if not entry["svg"]:
        raise SystemExit(f"no SVG glyph for {name}")
    # Prefer the requested style; fall back to whatever the free set ships.
    wanted = style if style in entry["svg"] else sorted(entry["svg"])[0]
    svg = entry["svg"][wanted]
    view_box = tuple(svg["viewBox"])
    if len(view_box) != 4:
        raise SystemExit(f"bad viewBox for {name}: {view_box}")
    return svg["path"], view_box  # type: ignore[return-value]


def collect(html: str) -> list[tuple[str, str]]:
    """Return the (style-class, icon-name) pairs used by a page, in order."""
    seen: list[tuple[str, str]] = []
    for style_class, name in ICON_RE.findall(html):
        pair = (style_class, name)
        if pair not in seen:
            seen.append(pair)
    return seen


def build_sprite(pairs: list[tuple[str, str]], icons: dict) -> str:
    lines = ["        <!-- fa-sprite:start -->",
             "        <!-- generated by scripts/build_icons.py; icons from the vendored Font Awesome metadata -->",
             '        <svg class="fa-sprite" width="0" height="0" aria-hidden="true" focusable="false">']
    for style_class, name in pairs:
        style = style_class[3:]  # "fa-solid" -> "solid"
        path, view_box = icon_path(icons, name, style)
        lines.append(
            f'            <symbol id="fa-{name}" viewBox="{" ".join(str(v) for v in view_box)}">'
            f'<path d="{path}"/></symbol>'
        )
    lines.append("        </svg>")
    lines.append("        <!-- fa-sprite:end -->")
    return "\n".join(lines)


def convert_uses(html: str, icons: dict) -> str:
    def repl(match: re.Match[str]) -> str:
        style_class, name = match.group(1), match.group(2)
        _, view_box = icon_path(icons, name, style_class[3:])
        return (
            f'<svg class="svg-inline--fa" viewBox="{" ".join(str(v) for v in view_box)}"'
            f' aria-hidden="true" focusable="false"><use href="#fa-{name}"/></svg>'
        )

    return ICON_RE.sub(repl, html)


# <svg class="svg-inline--fa"> tags already converted but missing the viewBox
VIEWBOX_RE = re.compile(
    r'<svg class="svg-inline--fa" aria-hidden="true" focusable="false"><use href="#fa-([a-z0-9-]+)"/></svg>'
)


def normalise_viewboxes(html: str, icons: dict) -> str:
    """Add the viewBox to <svg> wrappers written by an earlier run.

    Without a viewBox of its own the wrapper has no intrinsic ratio, so
    `height: 1em` leaves the width to resolve as 100% and the icon blows up to
    the width of its containing block.
    """
    style_of: dict[str, str] = {}
    for style_class, name in collect_users(html, icons):
        style_of[name] = style_class[3:]

    def repl(match: re.Match[str]) -> str:
        name = match.group(1)
        _, view_box = icon_path(icons, name, style_of.get(name, "solid"))
        return (
            f'<svg class="svg-inline--fa" viewBox="{" ".join(str(v) for v in view_box)}"'
            f' aria-hidden="true" focusable="false"><use href="#fa-{name}"/></svg>'
        )

    return VIEWBOX_RE.sub(repl, html)


def collect_users(html: str, icons: dict) -> list[tuple[str, str]]:
    """(style-class, name) pairs for every <use> already present in the page."""
    out: list[tuple[str, str]] = []
    for name in dict.fromkeys(re.findall(r'<use href="#fa-([a-z0-9-]+)"', html)):
        entry = icons.get(name, {})
        style = "brands" if "solid" not in entry.get("svg", {}) else "solid"
        out.append((f"fa-{style}", name))
    return out


def process(page: Path) -> None:
    html = page.read_text(encoding="utf-8")
    icons = load_icons()

    # The sprite must be built from the icons the page uses, including the
    # ones already converted to <use> by an earlier run.
    pairs = collect(html)
    for pair in collect_users(html, icons) + ALWAYS:
        if pair not in pairs:
            pairs.append(pair)
    if not pairs:
        print(f"  {page.name}: no icons found, skipping")
        return

    sprite = build_sprite(pairs, icons)

    body = html
    if SPRITE_RE.search(html):
        body = SPRITE_RE.sub("\n" + sprite + "\n", html)
    elif SPRITE_ANCHOR in html:
        body = html.replace(SPRITE_ANCHOR, SPRITE_ANCHOR + sprite + "\n", 1)
    else:
        raise SystemExit(f"{page}: could not find a <body> anchor for the sprite")

    converted = normalise_viewboxes(convert_uses(body, icons), icons)
    if converted == html:
        print(f"  {page.name}: already up to date ({len(pairs)} symbols)")
        return
    page.write_text(converted, encoding="utf-8")
    print(f"  {page.name}: {len(pairs)} symbols, {len(html) - len(converted):+d} bytes")


def main(argv: list[str]) -> int:
    pages = [REPO / name for name in (argv[1:] or DEFAULT_PAGES)]
    for page in pages:
        if not page.is_file():
            raise SystemExit(f"no such page: {page}")
        process(page)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
